services:
  _defaults:
    public: false
    autowire: true
    autoconfigure: true

  Harmony\Bundle\MenuBundle\Provider\ConfigurationMenuProvider:
    arguments:
      $factory: '@Harmony\Bundle\MenuBundle\Menu\MenuFactory'
    tags: ['knp_menu.provider']

  knp_menu.factory.class:
    class: Harmony\Bundle\MenuBundle\Menu\MenuFactory
  Harmony\Bundle\MenuBundle\Menu\MenuFactory: '@knp_menu.factory.class'